name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Copy JAR to EC2 instance
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa target/backend-0.0.1-SNAPSHOT.jar ec2-user@ec2-54-163-201-84.compute-1.amazonaws.com:~/

      - name: SSH to EC2 instance and run JAR
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-54-163-201-84.compute-1.amazonaws.com 'bash -s' << 'EOF'
            cd ~/
            java -jar backend-0.0.1-SNAPSHOT.jar
          EOF
