name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '17'

      - name: Replace placeholders in application.properties
        run: |
          SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          sed -i "s/\\${SPRING_DATASOURCE_USERNAME}/$SPRING_DATASOURCE_USERNAME/g" src/main/resources/application.properties

      - name: Build with Maven
        run: /opt/apache-maven-3.9.6/bin/mvn clean package -DskipTests

      - name: Run the jar
        run: java -jar ./target/backend-0.0.1-SNAPSHOT.jar

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
##      - name: Install SSH key
##        uses: webfactory/ssh-agent@v0.5.3
##        with:
##          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
#
##      - name: Copy JAR to EC2 instance
##        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa /home/runner/work/ani-backend/ani-backend/target/backend-0.0.1-SNAPSHOT.jar ec2-user@ec2-54-163-201-84.compute-1.amazonaws.com:~/
#
#      - name: SSH to EC2 instance and run JAR
#        run: |
#          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-54-163-201-84.compute-1.amazonaws.com 'bash -s' << 'EOF'
#            cd ~/
#            java -jar backend-0.0.1-SNAPSHOT.jar
#          EOF
