name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace placeholders in application.properties
        run: |
          SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          sed -i "s/\${SPRING_DATASOURCE_USERNAME}/$SPRING_DATASOURCE_USERNAME/g; \
                  s/\${SPRING_DATASOURCE_PASSWORD}/$SPRING_DATASOURCE_PASSWORD/g" src/main/resources/application.properties          

      - name: Build with Maven
        run: /opt/apache-maven-3.9.6/bin/mvn clean package -DskipTests

  kill:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Kill the already running application
        run: |
          PID=$(lsof -t -i:8080 2>/dev/null) || true
          if [ -n "$PID" ]; then
          echo "Killing process $PID"
          kill $PID
          else
          echo "Process not running"
          exit 0
          fi
  run:
    runs-on: ubuntu-latest
    needs: kill
    steps:
      - name: SSH to EC2 and start Java program
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod 777 /home/ec2-user/actions-runner/_work/ani-backend/ani-backend/target/backend-0.0.1-SNAPSHOT.jar
            nohup java -jar /home/ec2-user/actions-runner/_work/ani-backend/ani-backend/target/backend-0.0.1-SNAPSHOT.jar > output.log 2>&1 &

#  run:
#    runs-on: self-hosted
#    needs: kill
#    steps:
#      - name: Run the executable file
#        run: |
#          chmod 777 ./scripts/run.sh
#          bash ./scripts/run.sh

#      - name: Run the jar
#        run: |
#          nohup java -jar ./target/backend-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
#          echo $!
#          sleep 30
          
