name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace placeholders in application.properties
        run: |
          SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          sed -i "s/\${SPRING_DATASOURCE_USERNAME}/$SPRING_DATASOURCE_USERNAME/g; \
                  s/\${SPRING_DATASOURCE_PASSWORD}/$SPRING_DATASOURCE_PASSWORD/g" src/main/resources/application.properties          

      - name: Build with Maven
        run: /opt/apache-maven-3.9.6/bin/mvn clean package -DskipTests

  kill:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Kill the already running application
        run: kill $(lsof -t -i:8080)

  run:
    runs-on: self-hosted
    needs: kill
    steps:
      - name: Run the jar
        run: nohup java -jar ./target/backend-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
